### ISSUE TITLE
Stripping binaries

### ISSUE THREAD

**Issue by MoAlyousef** [IronOxidizer/gui-toolkit-benchmarks#41]
Hi

Interesting benchmark!
I think it would reasonable to strip all built binaries, since Rust tends to produce kinda bloated binaries because of the debug-info and symbols.

**Comment by IronOxidizer** [comment]
Thanks for adding this! I had it in the back of my mind but I completely forgot to cut an issue for it.

***Note*** for whoever implements this, we should also strip binaries for C++, C, and any other compiled language.
