### ISSUE TITLE
Add xamarin bench

### ISSUE THREAD

**Issue by IronOxidizer** [IronOxidizer/gui-toolkit-benchmarks#52]

**Comment by MoAlyousef** [comment]
AFAIR, xamarin and maui don’t support building on linux. With xamarin it was possible to build a linux app from windows. 

I think the 2 reasonable options for C# on linux are gtk-sharp (mono) and avalonia (dotnet core and mono)

**Comment by IronOxidizer** [comment]
Oh interesting, I was under the impression that they supported Linux, but today I learned 😅. Closing this for now, but will reopen when Linux support is added.
